### ISSUE TITLE
STM8L-Discovery Jupyter Notebook examples. GPIO, LCD controller, ADC, DAC, DMA

### ISSUE THREAD

**Issue by tanbras** [remotemcu/remcu_examples#1]
Hi,

https://github.com/tanbras/MCU_Experiments
This is my REMCU notebooks for STM8LDiscovery board. I want to share these examples for making it easier to learn STM8L chip.

I are looking forward to your confirmation.  
Tatiana

**Comment by ser-mk** [comment]
Hello Tatiana.
Thank you for your project! I am going to add the examples.
