### ISSUE TITLE
Why is 6 bytes a minimum read and write, use remcu_loadFrMem/remcu_store2mem. instead of 4 bytes or other？

### ISSUE THREAD

**Issue by hongshui3000** [remotemcu/remcu_examples#17]
Why is 6 bytes a minimum read and write, use remcu_loadFrMem/remcu_store2mem. instead of 4 bytes or other

#define MIN_MEM_OPERATION_SIZE 6

**Comment by ser-mk** [comment]
If I recall correctly, the requirement for 6 bytes as a minimum read and write is related to a bug in the 10.12 version of OpenOCD. I'll look into the details of the bug and check if there are any updates in the newer versions.

**Comment by ser-mk** [comment]
I checked the OpenOCD version for the mentioned bug, but couldn't confirm it for both old and new versions. The 6-byte limit in the code, written four years ago, might have been influenced by an encounter with an odd debugger. I can't recall the exact reason.
I have [changed the limit](https://github.com/remotemcu/remcu/commit/c3bb9bc322b3a60a30900894c24ea7eb3e3a450d) and I will rebuild the library soon.

**Comment by hongshui3000** [comment]
Got it, thanks for the reply

**Comment by ser-mk** [comment]
I've updated the prebuilt library https://github.com/remotemcu/prebuilt_libraries
Please check the latest version
